### ISSUE TITLE
inspector, extend vs app.

### ISSUE THREAD

**Issue by dbashford** [dbashford/MimosaEmberSkeleton#2]
Skeleton with `.extend`

![image](https://cloud.githubusercontent.com/assets/581127/4164987/45d1d0a0-34fd-11e4-91fb-372061c4c6f1.png)

With `App.`

![image](https://cloud.githubusercontent.com/assets/581127/4164979/36d47346-34fd-11e4-95a5-a53db32812e1.png)

**Comment by brzpegasus** [comment]
How about this?
https://github.com/dbashford/MimosaEmberSkeleton/compare/tests-assets-dot-mimosa...test-setup-alt2?expand=1

**Ember Inspector:**
![screen shot 2014-09-05 at 8 52 07 pm](https://cloud.githubusercontent.com/assets/1691398/4173668/845bf48c-3560-11e4-8486-a6a1a80fd1af.png)

**Console:**
![screen shot 2014-09-05 at 9 17 03 pm](https://cloud.githubusercontent.com/assets/1691398/4173734/a16f1024-3563-11e4-998b-95038b3cf82c.png)
